<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\framework\tests\Bing.Test.Shared\Bing.Test.Shared.csproj" />
  </ItemGroup>
</Project>