<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <RootNamespace>Bing.Logging.Sinks.Exceptionless.Tests</RootNamespace>
    <EnableDITestPackages>false</EnableDITestPackages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Logging.Sinks.Exceptionless\Bing.Logging.Sinks.Exceptionless.csproj" />
  </ItemGroup>
</Project>