language: csharp
mono: none
dist: focal
dotnet: 8.0
os:
#- osx
- linux
branches:
  only:
  - master
script:
- dotnet restore
- dotnet build -c Release
- dotnet test ./framework/tests/Bing.Data.Sql.Tests/Bing.Data.Sql.Tests.csproj -c Release -f net8.0 --no-restore --nologo
- dotnet test ./framework/tests/Bing.Dapper.Core.Tests/Bing.Dapper.Core.Tests.csproj -c Release -f net8.0 --no-restore --nologo
- dotnet test ./framework/tests/Bing.Dapper.Sqlite.Tests.Integration/Bing.Dapper.Sqlite.Tests.Integration.csproj -c Release -f net8.0 --no-restore --nologo
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: dotnet nuget push ${TRAVIS_BUILD_DIR}/output/release/*.nupkg -k ${NUGET_API_KEY}
#  on:
#    branch: master
#    os: linux
