<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net6.0;</TargetFrameworks>
    <RootNamespace>Bing.Core.PluginFixtures</RootNamespace>
    <AssemblyName>Bing.Core.PluginFixtures</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <Import Project="../../../../../common.props" />

  <ItemGroup>
    <ProjectReference Include="../../../../src/Bing.Core/Bing.Core.csproj" />
    <ProjectReference Include="../Bing.Core.PluginScanFixtures/Bing.Core.PluginScanFixtures.csproj" />
  </ItemGroup>
</Project>
