<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <RootNamespace>Bing.Dapper.Tests</RootNamespace>
    <EnableDITestPackages>false</EnableDITestPackages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Dapper.MySql\Bing.Dapper.MySql.csproj" />
    <ProjectReference Include="..\..\src\Bing.Dapper.Oracle\Bing.Dapper.Oracle.csproj" />
    <ProjectReference Include="..\..\src\Bing.Dapper.PostgreSql\Bing.Dapper.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\Bing.Dapper.SqlServer\Bing.Dapper.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Bing.Dapper.Sqlite\Bing.Dapper.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.28" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
    <PackageReference Include="MySqlConnector" Version="2.1.2" />
    <PackageReference Include="Npgsql" Version="6.0.11" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.7" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="3.21.90" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.4" />
  </ItemGroup>


</Project>
