<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net6.0;</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <BingTestingUseXunitDependencyInjection>true</BingTestingUseXunitDependencyInjection>
    <BingTestingUseDependencyInjectionLogging>true</BingTestingUseDependencyInjectionLogging>
    <BingTestingUseAspectCore>true</BingTestingUseAspectCore>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Aop.AspectCore\Bing.Aop.AspectCore.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Bing.Aop.AspectCore</RootNamespace>
    <XunitStartupFullName>Bing.Aop.AspectCore.Startup</XunitStartupFullName>
  </PropertyGroup>

</Project>
