<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />
  <PropertyGroup>
    <RootNamespace>Bing.Caching.FreeRedis.Tests</RootNamespace>
    <XunitStartupFullName>Bing.Caching.FreeRedis.Tests.Startup</XunitStartupFullName>
    <TestTfmsInParallel>false</TestTfmsInParallel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Caching.FreeRedis\Bing.Caching.FreeRedis.csproj" />
    <ProjectReference Include="..\Bing.Test.Shared\Bing.Test.Shared.csproj" />
  </ItemGroup>
</Project>
