<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\common.tests.props" />
  <PropertyGroup>
    <TargetFrameworks>net8.0;net6.0;</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Biz.Payments\Bing.Biz.Payments.csproj" />
  </ItemGroup>

</Project>
