//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.Mvc.ModelBinding.Metadata {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcModelBindingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcModelBindingResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.MvcModelBindingResource", typeof(MvcModelBindingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 不能作为 {1} 的值 的本地化字符串。
        /// </summary>
        internal static string AttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("AttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有为属性 &apos;{0}&apos; 指定值 的本地化字符串。
        /// </summary>
        internal static string MissingBindRequiredValueAccessor {
            get {
                return ResourceManager.GetString("MissingBindRequiredValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须指定值 的本地化字符串。
        /// </summary>
        internal static string MissingKeyOrValueAccessor {
            get {
                return ResourceManager.GetString("MissingKeyOrValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求正文不能为空 的本地化字符串。
        /// </summary>
        internal static string MissingRequestBodyRequiredValueAccessor {
            get {
                return ResourceManager.GetString("MissingRequestBodyRequiredValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 是无效的值 的本地化字符串。
        /// </summary>
        internal static string NonPropertyAttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("NonPropertyAttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的值无效 的本地化字符串。
        /// </summary>
        internal static string NonPropertyUnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("NonPropertyUnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段的值应该是数字 的本地化字符串。
        /// </summary>
        internal static string NonPropertyValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("NonPropertyValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为 {0} 指定的值无效 的本地化字符串。
        /// </summary>
        internal static string UnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("UnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 是无效的值 的本地化字符串。
        /// </summary>
        internal static string ValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 {0} 的值应该是数字 的本地化字符串。
        /// </summary>
        internal static string ValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("ValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 是无效的值 的本地化字符串。
        /// </summary>
        internal static string ValueMustNotBeNullAccessor {
            get {
                return ResourceManager.GetString("ValueMustNotBeNullAccessor", resourceCulture);
            }
        }
    }
}
