//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bing.DbDesigner.Systems.Domain {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bing.DbDesigner.Systems.Domain.SystemResource", typeof(SystemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 {0} 已存在 的本地化字符串。
        /// </summary>
        internal static string DuplicateModuleName {
            get {
                return ResourceManager.GetString("DuplicateModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块地址 {0} 已存在 的本地化字符串。
        /// </summary>
        internal static string DuplicateModuleUri {
            get {
                return ResourceManager.GetString("DuplicateModuleUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的应用程序 的本地化字符串。
        /// </summary>
        internal static string InvalidApplication {
            get {
                return ResourceManager.GetString("InvalidApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择角色 的本地化字符串。
        /// </summary>
        internal static string RoleIsEmpty {
            get {
                return ResourceManager.GetString("RoleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少选择一个用户 的本地化字符串。
        /// </summary>
        internal static string UsersIsEmpty {
            get {
                return ResourceManager.GetString("UsersIsEmpty", resourceCulture);
            }
        }
    }
}
