<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />
  <PropertyGroup>
    <RootNamespace>Bing.Dapper.Tests</RootNamespace>
    <EnableDITestPackages>false</EnableDITestPackages>
    <TestTfmsInParallel>false</TestTfmsInParallel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Dapper.MySql\Bing.Dapper.MySql.csproj" />
    <ProjectReference Include="..\Bing.Test.Shared\Bing.Test.Shared.csproj" />
    <ProjectReference Include="..\Bing.TestShare.MySql\Bing.TestShare.MySql.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RunSettingsFilePath>$(MSBuildProjectDirectory)\integration.runsettings</RunSettingsFilePath>
  </PropertyGroup>

</Project>
