<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <RootNamespace>Bing.Logging.BackgroundJobs.Tests</RootNamespace>
    <EnableDITestPackages>false</EnableDITestPackages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Logging.BackgroundJobs\Bing.Logging.BackgroundJobs.csproj" />
  </ItemGroup>
</Project>