<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <RootNamespace>Bing.Events.Tests</RootNamespace>
    <EnableDITestPackages>false</EnableDITestPackages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Events\Bing.Events.csproj" />
  </ItemGroup>
</Project>