<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <TargetFrameworks>net6.0;</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <BingTestingUseDependencyInjection>false</BingTestingUseDependencyInjection>
    <BingTestingUseLogging>false</BingTestingUseLogging>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.EntityFrameworkCore.Sqlite\Bing.EntityFrameworkCore.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Bing.Dapper.MySql\Bing.Dapper.MySql.csproj" />
    <ProjectReference Include="..\..\src\Bing.Dapper.Sqlite\Bing.Dapper.Sqlite.csproj" />
    <ProjectReference Include="..\Bing.Test.Shared\Bing.Test.Shared.csproj" />
  </ItemGroup>
</Project>