<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />
  <PropertyGroup>
    <RootNamespace>Bing.Caching.CSRedis.Tests</RootNamespace>
    <XunitStartupFullName>Bing.Caching.CSRedis.Tests.Startup</XunitStartupFullName>
    <TestTfmsInParallel>false</TestTfmsInParallel>
  </PropertyGroup>

  <PropertyGroup>
    <BingTestingUseXunitDependencyInjection>true</BingTestingUseXunitDependencyInjection>
    <BingTestingUseDependencyInjectionLogging>true</BingTestingUseDependencyInjectionLogging>
    <BingTestingUseAspectCore>true</BingTestingUseAspectCore>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Caching.CSRedis\Bing.Caching.CSRedis.csproj" />
    <ProjectReference Include="..\Bing.Test.Shared\Bing.Test.Shared.csproj" />
  </ItemGroup>

</Project>
