<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <RootNamespace>Bing.Logging.Hangfire.Tests.Integration</RootNamespace>
    <EnableDITestPackages>false</EnableDITestPackages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.36" />
    <PackageReference Include="Hangfire.MemoryStorage" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Logging.Hangfire\Bing.Logging.Hangfire.csproj" />
  </ItemGroup>
</Project>