<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <XunitStartupFullName>Bing.EventBus.Tests.Startup</XunitStartupFullName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EventBusFactoryAndNullBusTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.EventBus\Bing.EventBus.csproj" />
  </ItemGroup>

</Project>
