using System.Text;
using Bing.Analyzers.SourceGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Bing.Analyzers;

/// <summary>
/// 源代码生成器：用于生成 ChangTrackable 相关代码
/// </summary>
[Generator]
internal class ChangeTrackableSourceGenerator : ISourceGenerator
{
    /// <summary>
    /// 初始化代码生成器
    /// </summary>
    /// <param name="context">生成器初始化上下文</param>
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new DomainObjectBaseSyntaxReceiver());
    }

    /// <summary>
    /// 执行代码生成
    /// </summary>
    /// <param name="context">生成器执行上下文</param>
    public void Execute(GeneratorExecutionContext context)
    {
        var log = new StringBuilder();
        log.AppendLine($"// <auto-generated time='{DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss}' />");
        if (context.SyntaxReceiver is not DomainObjectBaseSyntaxReceiver receiver)
        {
            log.AppendLine("// warning: No classes detected for generation.");
        }
        else
        {
            var domainBaseSymbol = context.Compilation.GetTypeByMetadataName("Bing.Domain.Entities.DomainObjectBase`1");
            foreach (var classDecl in receiver.CandidateClasses)
            {
                var semanticModel = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
                if (ModelExtensions.GetDeclaredSymbol(semanticModel, classDecl) is not INamedTypeSymbol classSymbol)
                    continue;
                if (!IsDomainObjectBase(classSymbol, domainBaseSymbol))
                    continue;
                if (!ShouldGenerateChangeTracking(classDecl, classSymbol))
                    continue;

                var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
                    ? string.Empty
                    : classSymbol.ContainingNamespace.ToDisplayString();
                var className = classSymbol.Name;
                var properties = GetPublicInstanceProperties(classSymbol);
                log.AppendLine($"// Class {className}, Properties: {properties.Count}");

                GeneratePartialClassAndAddChangesMethod(context, namespaceName, className, properties);
            }

        }
        context.AddSource("Log.1.g.cs", SourceText.From(log.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// 检查类是否继承自 DomainObjectBase
    /// </summary>
    /// <param name="classSymbol">待检查的类符号。</param>
    /// <param name="domainBaseSymbol">DomainObjectBase 的符号定义。</param>
    /// <returns>如果类继承自 DomainObjectBase，则返回 true；否则返回 false。</returns>
    private bool IsDomainObjectBase(INamedTypeSymbol classSymbol, INamedTypeSymbol domainBaseSymbol)
    {
        for (var baseType = classSymbol.BaseType; baseType != null; baseType = baseType.BaseType)
        {
            if (domainBaseSymbol != null && SymbolEqualityComparer.Default.Equals(baseType.OriginalDefinition, domainBaseSymbol))
                return true;
            if (baseType.Name == "DomainObjectBase")
                return true;
        }
        return false;
    }

    /// <summary>
    /// 确定是否需要生成 ChangeTracking 代码
    /// </summary>
    /// <param name="classDecl">待检查的类语法节点。</param>
    /// <param name="classSymbol">待检查的类符号。</param>
    /// <returns>需要生成时返回 true；否则返回 false。</returns>
    private bool ShouldGenerateChangeTracking(ClassDeclarationSyntax classDecl, INamedTypeSymbol classSymbol)
    {
        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return false;
        return !classSymbol.GetMembers().OfType<IMethodSymbol>().Any(m => m.Name == "AddChanges" && m.IsOverride);
    }

    /// <summary>
    /// 生成部分类并添加 AddChanges 方法
    /// </summary>
    /// <param name="context">生成器执行上下文</param>
    /// <param name="namespaceName">命名空间</param>
    /// <param name="className">类名</param>
    /// <param name="properties">类属性</param>
    private void GeneratePartialClassAndAddChangesMethod(GeneratorExecutionContext context, string namespaceName, string className, List<BuilderPropertyInfo> properties)
    {
        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine($"// <auto-generated time='{DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss} />");
        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine();
        if (!string.IsNullOrWhiteSpace(namespaceName))
            sourceBuilder.AppendLine($"namespace {namespaceName};");

        var bodyScript = $$"""
                      public partial class {{className}}
                      {
                          /// <summary>
                          /// 添加变更列表
                          /// </summary>
                          protected override void AddChanges( {{className}} other )
                          {
                              {{properties.Render((p, i) =>
        {
            if (p.IsSkipGenerator()) { return string.Empty; }
            return $$"""
                                           AddChange( t=> t.{{p.Name}}, other.{{p.Name}} );

                                           """;
        }).Ident(2)}}
                          }
                      }
                      """;
        sourceBuilder.AppendLine(bodyScript);
        context.AddSource($"{namespaceName}.{className}.AddChanges.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// 构建属性信息
    /// </summary>
    struct BuilderPropertyInfo
    {
        /// <summary>
        /// 根据属性符号初始化生成器属性信息。
        /// </summary>
        /// <param name="property">待转换的属性符号。</param>
        public BuilderPropertyInfo(IPropertySymbol property) : this()
        {
            Type = property.Type.ToString();
            Name = property.Name;
            ParameterName = $"{Name[0].ToString().ToLower()}{Name.Remove(0, 1)}";
            BackingFieldName = $"_{ParameterName}";
        }

        /// <summary>
        /// 属性名称。
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 属性类型文本。
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// 对应的参数名称。
        /// </summary>
        public string ParameterName { get; set; }

        /// <summary>
        /// 对应的后备字段名称。
        /// </summary>
        public string BackingFieldName { get; set; }

        /// <summary>
        /// 判断属性是否应跳过生成器
        /// </summary>
        /// <returns>不应生成变更跟踪代码时返回 true；否则返回 false。</returns>
        public bool IsSkipGenerator()
        {
            if (Name == "Version" || Name == "IsDeleted")
                return true;
            return false;
        }
    }

    /// <summary>
    /// 获取类的公共实例属性
    /// </summary>
    /// <param name="classSymbol">类符号</param>
    /// <returns>按名称排序的公共实例属性信息。</returns>
    private List<BuilderPropertyInfo> GetPublicInstanceProperties(INamedTypeSymbol classSymbol)
    {
        var properties = new List<BuilderPropertyInfo>();
        while (classSymbol != null)
        {
            properties.AddRange(classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
                .Select(p => new BuilderPropertyInfo(p)));
            classSymbol = classSymbol.BaseType;
        }
        return properties.OrderBy(x => x.Name).ToList();
    }
}

/// <summary>
/// 为源代码生成提供文本格式化扩展。
/// </summary>
internal static class Extensions
{
    /// <summary>
    /// 为多行文本的后续行添加指定级别的缩进。
    /// </summary>
    /// <param name="source">待缩进的文本对象。</param>
    /// <param name="identLevels">缩进级别，每级四个空格。</param>
    /// <returns>应用缩进后的文本。</returns>
    public static string Ident(this object source, int identLevels)
    {
        var lines = source.ToString().TrimStart(' ').Split('\n');
        var ident = new string(' ', identLevels * 4);
        return string.Join("\n", lines.Select((x, i) => $"""{(i > 0 ? ident : "")}{x}"""));
    }

    /// <summary>
    /// 使用模板渲染序列中的每个元素。
    /// </summary>
    /// <typeparam name="T">序列元素类型。</typeparam>
    /// <param name="source">待渲染的元素序列。</param>
    /// <param name="template">将元素转换为文本的模板。</param>
    /// <param name="separator">元素文本之间的分隔符。</param>
    /// <returns>拼接后的文本。</returns>
    public static string Render<T>(this IEnumerable<T> source, Func<T, string> template, string separator = "")
    {
        return string.Join(separator, source.Select(template));
    }

    /// <summary>
    /// 使用带索引的模板渲染序列中的每个元素。
    /// </summary>
    /// <typeparam name="T">序列元素类型。</typeparam>
    /// <param name="source">待渲染的元素序列。</param>
    /// <param name="template">将元素及其索引转换为文本的模板。</param>
    /// <param name="separator">元素文本之间的分隔符。</param>
    /// <returns>拼接后的文本。</returns>
    public static string Render<T>(this IEnumerable<T> source, Func<T, int, string> template, string separator = "")
    {
        return string.Join(separator, source.Select(template));
    }
}
