<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\framework.tests.props" />

  <PropertyGroup>
    <RootNamespace>Bing.Dapper.Tests</RootNamespace>
    <XunitStartupFullName>Bing.Dapper.Tests.Startup</XunitStartupFullName>
  </PropertyGroup>

  <PropertyGroup>
    <BingTestingUseXunitDependencyInjection>true</BingTestingUseXunitDependencyInjection>
    <BingTestingUseDependencyInjectionLogging>true</BingTestingUseDependencyInjectionLogging>
    <BingTestingUseAspectCore>true</BingTestingUseAspectCore>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bing.Dapper.Oracle\Bing.Dapper.Oracle.csproj" />
    <ProjectReference Include="..\Bing.Test.Shared\Bing.Test.Shared.csproj" />
  </ItemGroup>
</Project>